### ISSUE TITLE
Implement all expr_form types

### ISSUE THREAD

**Issue by lucidd** [SUSE/salt-netapi-client#103]
[all expr_forms](https://docs.saltstack.com/en/latest/ref/clients/)
maybe some relevant [documenatation](https://docs.saltstack.com/en/latest/topics/targeting/compound.html)
- [ ] pcre - Perl style regular expression
- [x] grain - Match based on a grain comparison
- [ ] grain_pcre - Grain comparison with a regex
- [ ] pillar - Pillar data comparison
- [ ] pillar_pcre - Pillar data comparison with a regex
- [ ] range - Use a Range server for matching
- [ ] compound - Pass a compound match string

Work in progress  [branch](https://github.com/SUSE/saltstack-netapi-client-java/tree/full-expr-form-support)

**Comment by mchugh19** [comment]
The code has changed lots since this was opened. Is the recorded state still accurate?

**Comment by renner** [comment]
Unfortunately it looks like the checklist of unimplemented matchers is still accurate, even though a lot of other code has changed. The referenced [branch] (https://github.com/SUSE/saltstack-netapi-client-java/tree/full-expr-form-support) does not seem to exist anymore, though. @lucidd, does your patch live on somewhere else meanwhile?

**Comment by lucidd** [comment]
the branch only contained grains so far and that part got merged.

**Comment by mcalmer** [comment]
Seems that `expr_form` is deprecated and must be replaced very soon:

```
DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.
```

salt is currently at `Oxygen` release and `Fluorine` will be the next one.

**Comment by renner** [comment]
Closing this issue as we have #226 merged meanwhile. Created a [new issue](https://github.com/SUSE/salt-netapi-client/issues/103#issuecomment-352685882) with the contents of the last comment.
