### ISSUE TITLE
SaltStackClientTest runs shows Slf4jNotifierError stacktraces

### ISSUE THREAD

**Issue by renner** [SUSE/salt-netapi-client#138]
This is not a serious issue, but it would be nice to get rid of those stacktraces in the test output, see for instance [here](https://travis-ci.org/SUSE/saltstack-netapi-client-java/builds/95994247#L1824) (and go to line 1824 by manual scrolling if necessary).

**Comment by admd** [comment]
After updating Wiremock version to 2.5.1 in pom, I can't reproduce this issue anymore.

**Comment by renner** [comment]
Thanks for this finding @admd! I can confirm that and will update wiremock in `pom.xml` permanently.

**Comment by renner** [comment]
I updated wiremock with dd7a5e3bbb1577cd00e3c7a565d5579a0bd0ae9a. It looks good to me, no stacktraces anymore.
