### ISSUE TITLE
Getting JSON exception when Saltstack returns an error

### ISSUE THREAD

**Issue by manikantag** [SUSE/salt-netapi-client#162]
Hi, I found this project very useful, and using it actively. 

I m facing an issue whenever Saltstack returns some syntax or template error, library is not able unmarshall the API returned JSON to Object and is causing JSON unmarshall exception.

Example error response from Salt API server:

	{"return": [{"ubuntu": ["Rendering SLS 'base:test' failed: Jinja error: 'NamespacedDictWrapper' object has no attribute '__call__'\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/utils/templates.py\", line 366, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 742, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\", line 6, in top-level template code\nAttributeError: 'NamespacedDictWrapper' object has no attribute '__call__'\n\n; line 6\n\n---\ntest-file:\n  file.append:\n    - name: /data/test.txt\n    - text\n      - Test from API\n      - URL={{pillar('TM_URL')}}    <======================\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/utils/templates.py\", line 366, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n[...]\n---"]}]}

**Comment by lucidd** [comment]
Glad to hear that you find this project useful. We addressed this issue recently and its already in the master branch. What you would get now is something like this.

```
{ubuntu=Error(GenericSaltError(["Rendering SLS 'base:test' failed: Jinja error: 'NamespacedDictWrapper' object has no attribute '__call__'\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/utils/templates.py\", line 366, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 742, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\", line 6, in top-level template code\nAttributeError: 'NamespacedDictWrapper' object has no attribute '__call__'\n\n; line 6\n\n---\ntest-file:\n  file.append:\n    - name: /data/test.txt\n    - text\n      - Test from API\n      - URL={{pillar('TM_URL')}}    <======================\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/utils/templates.py\", line 366, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File \"/usr/lib/python2.7/dist-packages/jinja2/environment.py\", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n[...]\n---"], Expected BOOLEAN but was BEGIN_ARRAY))}
```

Instead of throwing an exception you now get a `GenericSaltError` or in some cases a more specific error instead of the result value. This is handled on a per minion basis so successful minions results are unaffected by error results. If you have any questions about this feel free to ask here. :smile: 

We plan on making a new release soon but if you want to try it out now just checkout the code and use `mvn install` to put the new version in you maven cache.

**Comment by manikantag** [comment]
Excellent :) Currently we are moving to staging. Will wait for the next release, unless we see a road blocker with current one. Thanks.
