### ISSUE TITLE
add the cp module to execute the function like 'fun='cp.push',fun='cp.get_file''

### ISSUE THREAD

**Issue by caidongqing** [SUSE/salt-netapi-client#164]
I want to excute the folloow salt-api with salt-netapi-client。 Has the funtion already been added,or I did not find it? Someone show me a model please,thank you!

curl -k https://192.168.1.72:8000 -H "Accept: application/x-yaml"         -H "X-Auth-Token: c203344e84448e60582acc662d0108d69948dbfd"         -d client=local  -d tgt='slave1' -d fun='cp.push' -d arg="/opt/tmp/tmp1.tar.gz"

**Comment by renner** [comment]
@caidongqing: Hello, I will give you an example. We do not (yet) have built-in support for the `cp` execution module, but this is still really easy to achieve:

```java
// Create the client object
SaltClient client = new SaltClient(URI.create("https://192.168.1.72:8000"));

// Prepare the call
List<String> arg = new LinkedList<>();
arg.add("/opt/tmp/tmp1.tar.gz");
LocalCall<Boolean> call = new LocalCall<>("cp.push", Optional.of(arg), Optional.empty(), new TypeToken<Boolean>(){});
Target<List<String>> target = new MinionList("slave1");

// Perform the call and print the result
Map<String, Result<Boolean>> result = call.callSync(client, target, "user", "password", AuthModule.AUTO);
result.get("slave1").result().ifPresent(r -> System.out.println("Result: " + r));
```

Any calls can be executed in this way, you only need to figure out what Salt will actually return for each targeted minion. In this case it seems to be a `Boolean` so we can simply create a `LocalCall<Boolean>`. Let me know if this works for you.

**Comment by caidongqing** [comment]
thank you,It works perfectly。yestody I also solved it with creating a class Cp In 'modules'。

**Comment by renner** [comment]
I am glad that it works for you, feel free to contribute your `Cp` class via a pull request. Thank you!
