### ISSUE TITLE
Json parsing issue with ResultInfo class 

### ISSUE THREAD

**Issue by snambi** [SUSE/salt-netapi-client#177]
http://stackoverflow.com/questions/40558646/gson-parsing-error-with-salt-net-api

ResultInfo class contains `StartTime` class
`public class ResultInfo {
    @SerializedName("StartTime")
    private StartTime startTime;
`

But StartTime class has 
`public class StartTime {
    private final String dateString;`

I think this creates a problem in parsing json. Please take a look at the SOF thread.

**Comment by lucidd** [comment]
You have to use the same type adapters the library is using. You can find a full example [here](https://github.com/SUSE/salt-netapi-client/blob/master/src/main/java/com/suse/salt/netapi/parser/JsonParser.java#L45).
