### ISSUE TITLE
ClientConfig.SOCKET_TIMEOUT too low if one host is down?

### ISSUE THREAD

**Issue by smatei** [SUSE/salt-netapi-client#184]
The default read timeout is 10 seconds. Using that default timeout on a master/api with default timeout (no change in master config), I get timeout exception if a host happens to be down. Raising the read timeout above 15 seconds, that is 16 or higher will return the json that does not contain the missing host. That should be the right behavior. Should ClientConfig.SOCKET_TIMEOUT be a little bit higher (maybe 20 seconds) so that one minion timeout does not affect the response when using default settings for library+api+master?

For me it would be easy to override ClientConfig.SOCKET_TIMEOUT, but I think the default should work even if something goes wrong.

**Comment by renner** [comment]
@smatei: Indeed I just did some testing with the default settings and I agree: the default `SOCKET_TIMEOUT` should be longer than the Salt defaults so you won't get timeout exceptions. Fixed it with #208.

By the way, @osbominix: I enhanced your recently added comment a bit with 4190cde15fca64de79610ade31e92366038b16b8 which is only valid with that patch.

**Comment by renner** [comment]
Closing this, should be fixed with the merge of #208.
