### ISSUE TITLE
How to use token authentication for subsequent requests

### ISSUE THREAD

**Issue by jar-ek** [SUSE/salt-netapi-client#188]
Hi,
Sorry for posting here but I didn't know where to go.
Can someone give me an example how to use Token authentication for subsequent requests after login?
I need to use it in web application but could not find any example of this.
Thanks
Jarek

**Comment by lucidd** [comment]
Hey. This is the right place to ask so no worries :smile:. After you called login and successfully authenticated the same client instance will automatically reuse the token on subsequent requests for alle call* methods that don't take credentials for the ad-hoc authentication.

**Comment by jar-ek** [comment]
Thanks for the response Lucidd. I admit I don't fully understand how it works yet :-)
Somehow I get the pemissions exception when I run the call from other bean in the same session (login is scuccessful):
com.suse.salt.netapi.exception.SaltUserUnauthorizedException: Salt user does not have sufficient permissions

It goes like this (all beans are session scoped):
login.xhtml -> LoginBean -> run.xthml -> TaskRunner bean (which calls Task POJO) -> results.xhtml

LoginBean:
`

@Named(value = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private static final String SALT_API_URL = "http://localhost:8000";

    private String username;
    private String password;

    private boolean loggedIn;
    
    //login token
    private Token token = null;

    public Token getToken() {
        return token;
    }

    public String doLogin() throws SaltException {
        
		//after susscessful login open "run" page 
        try {
			SaltClient client = new SaltClient(URI.create(SALT_API_URL));

			//Now try to login and get login token
			token = client.login(username, password, PAM);

			if (!token.getToken().isEmpty()) {
				loggedIn = true;
				return "/secured/run.xhtml?faces-redirect=true";
			}

			// Set login ERROR
			FacesMessage msg = new FacesMessage("Login error!", "ERROR MSG");
			msg.setSeverity(FacesMessage.SEVERITY_ERROR);
			FacesContext.getCurrentInstance().addMessage(null, msg);

        }
        catch (SaltException exception) {
            System.out.println(exception.toString());
        }
		
		//if login failed go back to login page
        return "login";
        
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
	
}
`
TaskRunner bean:
`@Named("taskRunner")
@SessionScoped

public class TaskRunner implements Serializable {

    private static final long serialVersionUID = 7765876811740798583L;

    private Token token;

    @Inject LoginBean login;

    //Output from the job
    private Map<String, Result<String>> results = null;

    public Map<String, Result<String>> getResults() {
        setResults();
        return results;
    }

    private void setResults() {
        token = login.getToken();       
        Task task = new Task();
        results = task.getResults();
    }

    public String submitButton() {
        results = getResults();
        return goToResultsPage();
    }

    private String goToResultsPage() {
        return "/secured/results.xhtml?faces-redirect=true";
    }

}`

Task POJO:

`class Task {
    
    private static final String SALT_API_URL = "http://localhost:8000";
    private final SaltClient client = new SaltClient(URI.create(SALT_API_URL));
    String saltCommand = "/opt/scripts/echo.sh";
    String saltSystems = "*";
    private Map<String, Result<String>> results = null;

    //get the results :-)
    private Map<String, Result<String>> runTask() {

        Target<String> globTarget = new Glob(saltSystems);
        try {
            Map<String, Result<String>> minionResults;
            minionResults = Cmd.run(saltCommand).callSync(client, globTarget);
            return minionResults;
        } catch (SaltException ex) {
            Logger.getLogger(TaskRunner.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }

    }

    public Map<String, Result<String>> getResults() {
        results = runTask();
        return results;
    }

}`

**Comment by jar-ek** [comment]
Ok, I think I know what was wrong - I built new client in the Task class which was not authenticated...

**Comment by renner** [comment]
Good to hear that it works for you now, @jar-ek! Let us know if you have any further questions.
