### ISSUE TITLE
websocket failed to recognize. Deployment.exception: Handshake error

### ISSUE THREAD

**Issue by KrishnaNagar** [SUSE/salt-netapi-client#202]
trying to listen for events on salt's event bus. 
salt version report:
Salt: 2015.5.10
         Python: 2.7.12 (default, Dec  6 2016, 12:45:38)
         Jinja2: 2.8
       M2Crypto: 0.25.1
 msgpack-python: 0.4.8
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.12
          ioflo: Not Installed
          PyZMQ: 14.0.0
           RAET: Not Installed
            ZMQ: 4.0.8
           Mako: Not Installed
        Tornado: 4.4.2
        timelib: 0.2.4
       dateutil: 2.5.3

postman request:
GET /ws HTTP/1.1
Host: 10.214.229.16:8000
Content-Type: application/json
X-Auth-Token: 0de9a94ef8c44b73a1f82feed26009dd8d293f2e
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: s65VsgHigh7v/Jcf4nXHnA==
Upgrade: websocket
Connection: Upgrade
Cache-Control: no-cache
Postman-Token: 5a78cf06-b177-0416-f647-3da1c4ef09a6

response generated:

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <title>404 Not Found</title>
        <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
    </head>
    <body>
        <h2>404 Not Found</h2>
        <p>The path '/ws' was not found.</p>
        <pre id="traceback"></pre>
        <div id="powered_by">
            <span>
        Powered by 
                <a href="http://www.cherrypy.org">CherryPy 8.1.2</a>
            </span>
        </div>
    </body>
</html>

can you help me out with the solution for this above problem??

**Comment by lucidd** [comment]
the salt [documentation](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html) says that ws4py is required. Do you have that installed?

**Comment by KrishnaNagar** [comment]
Yes, It is installed.

**Comment by lucidd** [comment]
you seem to use quite an old version of salt. It should still work but is there any chance you can upgrade to something newer and see if you can reproduce the issue there?

**Comment by KrishnaNagar** [comment]
Yeah, upgrading the salt version solved my problem. Thanks

**Comment by renner** [comment]
That is good to hear @KrishnaNagar, let us know in case you experience other problems.

**Comment by xiaosazixian** [comment]
@KrishnaNagar 
which version you upgrading
