### ISSUE TITLE
 javax.websocket.DeploymentException: Handshake response not received

### ISSUE THREAD

**Issue by xiaosazixian** [SUSE/salt-netapi-client#206]
![image](https://user-images.githubusercontent.com/12694566/27782902-cd7c65d8-6006-11e7-926b-567e67653721.png)
com.suse.salt.netapi.exception.SaltException: javax.websocket.DeploymentException: Handshake response not received.
	at com.suse.salt.netapi.event.EventStream.initializeStream(EventStream.java:108)
	at com.suse.salt.netapi.event.EventStream.<init>(EventStream.java:84)
	at com.suse.salt.netapi.client.SaltClient.events(SaltClient.java:544)

**Comment by lucidd** [comment]
Can you verify that you have have `ws4py` installed for the websocket support to work in salt?

**Comment by xiaosazixian** [comment]
I have ws4py installed,but i didn't konw is there any other configuration

**Comment by renner** [comment]
@xiaosazixian: I am closing this issue as there was no progress since a long time. Please feel free to reopen report a new issue in case you still experience those problems or in case you have further questions.

**Comment by nadezhdabelan** [comment]
com.suse.salt.netapi.exception.SaltException: javax.websocket.DeploymentException: The HTTP response from the server [404] did not permit the HTTP upgrade to WebSocket  -  error, code the same like from xiaosazixian
