### ISSUE TITLE
When will the next version be released

### ISSUE THREAD

**Issue by xiaosazixian** [SUSE/salt-netapi-client#207]

**Comment by renner** [comment]
Hey @xiaosazixian, we will prepare the next release (0.12) pretty soon, hopefully within the next two weeks. Hold on for it just a little while, which of the [latest changes](https://github.com/SUSE/salt-netapi-client/pulls?q=is%3Apr+milestone%3A%22Version+0.12%22+is%3Aclosed) are you waiting on in particular?

**Comment by xiaosazixian** [comment]
@renner thank you so much
The bug fix in #200 ，Result < R > instead of just R。

**Comment by renner** [comment]
Okay, thank you for your patience @xiaosazixian! I will proceed with the 0.12 release these days.

**Comment by renner** [comment]
@xiaosazixian: Yesterday I released 0.12 to maven central, [see here](https://search.maven.org/#artifactdetails%7Ccom.suse.salt%7Csalt-netapi-client%7C0.12.0%7Cjar). Have a lot of fun with the new release and let us know if there is any questions!

**Comment by xiaosazixian** [comment]
@renner ok, i will try it.
