### ISSUE TITLE
How Can I List All minions by getMinions()?

### ISSUE THREAD

**Issue by SwinBlackSea** [SUSE/salt-netapi-client#215]
code:
```java
 SaltClient client = new SaltClient(URI.create(SALT_API_URL));
        client.getConfig().put(ClientConfig.SOCKET_TIMEOUT, 3000);
        Token token = null;
        Map<String, Map<String, Object>> minions = null;
        try {
            client.login(USER, PASSWORD, AuthModule.PAM);
           minions = client.getMinions();
         }
```
When I try to get all minions by using getMininons(),an error occured to me:
     "Caused by: java.net.SocketTimeoutException: Read timed out"
But when all minions test.ping success ,I can get all minions.however if any minion can not test.ping,the error above come to me .

    Thank for your reply.

**Comment by mbologna** [comment]
Hi @SwinBlackSea !
Can you check that your `SALT_API_URL` is properly responding via HTTP?

E.g.:
What does `curl -sS http://SALT_API_URL/login -c ~/cookies.txt -H 'Accept: application/json' -d username=USER -d password=PASSWORD -d eauth=pam` returns?

I reviewed and made some edits to your code, see the following:

```java
import com.suse.salt.netapi.client.SaltClient;
import com.suse.salt.netapi.config.ClientConfig;

import java.net.URI;
import java.util.Map;

public class Test {

    private static final String SALT_API_URL = "http://localhost:8000";

    public static void main(String args[]) {
        SaltClient client = new SaltClient(URI.create(SALT_API_URL));
        client.getConfig().put(ClientConfig.SOCKET_TIMEOUT, 3000);
        Map<String, Map<String, Object>> minions = null;
        try {
            client.login("saltdev", "saltdev", AuthModule.PAM);
            minions = client.getMinions();
            System.out.println(minions.keySet().size());
        }
        catch (Exception e) {
            // HTTP 418!
        }
    }
}
```
 
and I tested it successfully against a Docker setup deployed using instruction written [here](https://github.com/mbologna/docker-salt#usage).

**Comment by SwinBlackSea** [comment]
@mbologna I am so sorry for no reply to you timely. but I think your answer is not appropriate to me because I can also get all minions if all minions can test.ping successfully.but if just one minion failed by test.ping, the problem will happen.

the background of this issue is that I want to know how many minion is died and how many minions alive.but now I use a method by monitoring events in master ,because minions ping master  regularly.
thank you very much .if you have a more elegant method in this issue ,please tell me timely!

**Comment by amendlik** [comment]
@SwinBlackSea Have you tried a longer socket timeout? It takes at least 5 seconds to determine that a test.ping has failed. It looks like your socket will timeout after 3 seconds.

You may also want to look at some of the [manage runner functions](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.manage.html#module-salt.runners.manage), such as [manage.present](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.manage.html#salt.runners.manage.present).

**Comment by mbologna** [comment]
@SwinBlackSea now I understand your problem.
In order to fetch all the minions that are either up or down, you should not use `test.ping`, but rather, as @amendlik pointed out, you should use a runner function.
In our case, a simple Java example that uses the runner function:

```java
package com.suse.salt.netapi.examples;

import com.suse.salt.netapi.AuthModule;
import com.suse.salt.netapi.calls.runner.Manage;
import com.suse.salt.netapi.client.SaltClient;
import com.suse.salt.netapi.config.ClientConfig;
import com.suse.salt.netapi.exception.SaltException;
import com.suse.salt.netapi.results.Result;

import java.net.URI;
import java.util.List;

/**
 * Example code calling runner functions.
 */
public class Runner {

    private static final String SALT_API_URL = "http://localhost:8000";
    private static final String USER = "saltdev";
    private static final String PASSWORD = "saltdev";

    public static void main(String[] args) throws SaltException {
        // Init the client
        SaltClient client = new SaltClient(URI.create(SALT_API_URL));
        client.getConfig().put(ClientConfig.SOCKET_TIMEOUT, 30000);
        Result<List<String>> resultDown = Manage.down(false)
                .callSync(client, USER, PASSWORD, AuthModule.PAM);
        System.out.println("manage.down: " + resultDown);
        Result<List<String>> resultUp = Manage.up()
                .callSync(client, "saltdev", "saltdev", AuthModule.PAM);
        System.out.println("manage.up: " + resultUp);
    }
}
```

In my setup, the output is:

```
manage.down: Result([saltminion7])
manage.up: Result([saltminion1, saltminion2, saltminion3, saltminion4, saltminion5, saltminion6, saltminion8, saltminion9])
```

**Comment by SwinBlackSea** [comment]
@mbologna Thank you for you help very much, I am so superised by your programme , I test it in my code and I get correct reply from salt-master
and your programme is better than mine.
Thank you !

**Comment by renner** [comment]
I am glad that this works for you @SwinBlackSea, closing this issue for now. Feel free to reopen if you still see any problems.
