### ISSUE TITLE
When will 0.14.0 release?

### ISSUE THREAD

**Issue by jeffsigmon** [SUSE/salt-netapi-client#231]
I really want to take advantage of the new compound targeting code.

Thanks!

**Comment by lucidd** [comment]
I don't know of any official plans for the 0.14.0 but if you really need the compound matcher now its not hard to either build the master branch and use that or copy the compound matcher to your own codebase until it is released. @renner  can probably say more about the release schedule.

**Comment by jeffsigmon** [comment]
No worries, I'v created my own build of the master branch - that should hold me over until the official release.

**Comment by renner** [comment]
Hey @jeffsigmon, I hope we can release 0.14.0 even before the end of this week, or at least next week. Sorry for the delay!
