### ISSUE TITLE
Doesn't work with API served on sub-path

### ISSUE THREAD

**Issue by danh-fissara** [SUSE/salt-netapi-client#237]
Hi,
I noticed that any path as part of the the base URL gets ignored, because the (`/run`, `/minions` etc.) paths passed to `URI.resolve()` are absolute and so replace whatever was specified in `ClientConfig.URL`:

https://github.com/SUSE/salt-netapi-client/blob/fda385a16c84f59f097c60336dc4b9891fdf3355/src/main/java/com/suse/salt/netapi/client/impl/HttpClientConnection.java#L166

It looks like trivial fix, but I see the code's moved on a fair bit since `0.14.0`, and am not sure if it's still an issue.

**Comment by renner** [comment]
Hey @danh-fissara, we are about to release [version 1.0.0](https://github.com/SUSE/salt-netapi-client/milestone/11) soon and indeed many things are going to change also regarding the client configuration. I don't really understand though what is your question: the API should always be running on a specific URL and those endpoints like `/run` should actually be appended by the call to `resolve()`. Maybe @lucidd can help on this topic, too.

**Comment by danh-fissara** [comment]
Hey, thanks for the response. To clarify, we're running the API behind a proxy, so a request to `https://example.com:443/api/run` gets proxied to the salt-api as `http://localhost:8000/run`.

Anyway, even without the proxy, the docs seem to say running at sub-paths is supported via the `root_prefix` config:
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#a-rest-api-for-salt

> root_prefix
> : /
>     A URL path to the main entry point for the application. This is useful for serving multiple applications from the same URL.

**Comment by lucidd** [comment]
@danh-fissara hey yeah you are right the problem is the leading `/` we added everywhere. I think it makes sense to support your use case and it should be easy to find all the endpoints strings in the code and remove the `/` there.

**Comment by renner** [comment]
Okay, #241 was merged so I expect this issue to be fixed with the next release (or current master). Please let us know if it works for you or if there is any further issues, @danh-fissara.
