### ISSUE TITLE
websocket handshake 500,  javax.websocket-api.jar conflict

### ISSUE THREAD

**Issue by KinoamyFx** [SUSE/salt-netapi-client#240]
# problem

I use salt-netapi-client in my web app, 

but chrome could not establish websocket session, error code 500.

I found when handshake the WsServerContainer could not be casted to ServerContainer, 
after I googled , I found javax.websocket-api will conflict in Tomcat7

# solution

So I excluded the javax.websocket-api in salt-netapi-client, it works well now.

# suggestion
remove 
``` xml
    <dependency>
      <groupId>javax.websocket</groupId>
      <artifactId>javax.websocket-api</artifactId>
      <version>1.1</version>
      <scope>compile</scope>
    </dependency>
```

or change it to scope provided?

**Comment by renner** [comment]
Hey @KinoamyFx, thanks for reporting this. Removing the dependency would break compilation, but I created a PR to set the scope to `provided`, see #244. Once this is merged we should be able to close this issue.
