### ISSUE TITLE
Response code: 500

### ISSUE THREAD

**Issue by chengpengvb** [SUSE/salt-netapi-client#274]
my error is 
![QQ截图20190523012643](https://user-images.githubusercontent.com/28288567/58195136-dbedb380-7cf9-11e9-9bfe-6e2cc8405fcc.png)

config is
![QQ截图20190523012754](https://user-images.githubusercontent.com/28288567/58195238-19ead780-7cfa-11e9-87fb-c7ad66e567a1.png)
![QQ截图20190523012812](https://user-images.githubusercontent.com/28288567/58195244-1ce5c800-7cfa-11e9-98b2-39513f3e871d.png)

**Comment by chengpengvb** [comment]
this is my code 
![QQ截图20190523012433](https://user-images.githubusercontent.com/28288567/58195044-a3e67080-7cf9-11e9-9b36-7e87608de0d3.png)

**Comment by chengpengvb** [comment]
The problem is solved, my version is too low, it can be upgraded.

**Comment by renner** [comment]
Hey @chengpengvb, sorry for the late reply. I am glad that your problem is solved meanwhile, closing this issue.
