### ISSUE TITLE
0.16.0 should be 1.0.0

### ISSUE THREAD

**Issue by britho** [SUSE/salt-netapi-client#275]
I noticed that the differences between 0.14.0 and 0.16.0 were vast.  There are a lot of breaking changes (e.g., deprecation/renaming of classes and packages).  Shouldn't this have been a 1.0.0 update instead of 0.16.0 following semver, or does the Java community function under a different set of semver assumptions?

**Comment by lucidd** [comment]
pre 1.0.0 versions are treated special in semver. Here is the relevant part from semver documentation.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by britho** [comment]
That makes a lot more sense.  I should do my homework in the future.  Thanks for taking the time to respond.
