### ISSUE TITLE
POST /minions which returns job id not implemented?

### ISSUE THREAD

**Issue by seaguest** [SUSE/salt-netapi-client#290]
Hi,

I didn't find this rest api:
```
POST(**kwargs)
Start an execution command and immediately return the job id

POST /minions
```

best regards

**Comment by renner** [comment]
Hello @seaguest, sorry for the delayed reply! In fact the implementation of that endpoint had been removed in 2017 (with fc16d281ef7fa4b6bc5ff5592c1f46ba18fe0143). This endpoint is from our perspective not really needed as every call to an execution module can be done by calling the root (`/`) endpoint of the API, which is the method we would like to promote.

This would be a minimal example to perform the call from the [upstream docs](https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Minions.POST) based on the [Calls example](https://github.com/SUSE/salt-netapi-client/blob/master/src/test/java/com/suse/salt/netapi/examples/Calls.java):

``` java
// Prepare client and authentication
SaltClient client = new SaltClient(URI.create(SALT_API_URL), new HttpAsyncClientImpl(HttpClientUtils.defaultClient()));
AuthMethod auth = new AuthMethod(new PasswordAuth("user", "password", AuthModule.AUTO));

// Setup the target and run the call
Target<String> globTarget = new Glob("*");
Status.diskusage().callAsync(client, globTarget, auth)
        .thenAccept(result ->  System.out.println("Job ID: " + result.get().getJid()));
```

**Comment by renner** [comment]
Closing the issue as the original question should be answered. Please reach out or reopen if there is further questions.
